### ISSUE TITLE
Support 3.10 and master

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-local_assessfreq#62]
PHPUnit upgrade landed to 3.10 and master. This broken travis checks in master branch. Would be nice to fix it.

**Comment by mattporritt** [comment]
@dmitriim 
I know we'll need to make changes to the unit tests to work with master as they use a newer version of PHPUnit, but initial testing show that these work with older versions.
We'll also need to remove the 3.5 Moodle checks from the master plugin branch. There is a 3.5 branch of the plugin that covers that.
Do we have a example travis file that works for plugins across versions: 3.7, 3.8, 3.9, 3.10 and master?

**Comment by mattporritt** [comment]
Based on initial testing, we need the following branches
* MOODLE_35 -> Moodle 3.5 to 3.8 (already exists)
* MOODLE_39 -> Moodle 3.9 to 3.10 (needs to be created)
* master -> Moodle master (branch exists, but code needs to be fixed)

**Comment by mattporritt** [comment]
I've created the versions we need and updated the project readme so we know what branch maps to what moodle versions.
I've also got the code working across all versions/branches.
Next:
* [ ] add github action setup for the project to replace travis automated testing
* [ ] fix unit tests as required
